// tslint:disable
/**
 * Zigzag.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    BookDto,
} from './';

/**
 * @export
 * @interface AddBookCommand
 */
export interface AddBookCommand {
    /**
     * @type {BookDto}
     * @memberof AddBookCommand
     */
    book?: BookDto;
}
