// tslint:disable
/**
 * Zigzag.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BookDto
 */
export interface BookDto {
    /**
     * @type {string}
     * @memberof BookDto
     */
    id?: string;
    /**
     * @type {string}
     * @memberof BookDto
     */
    title?: string | null;
    /**
     * @type {string}
     * @memberof BookDto
     */
    author?: string | null;
    /**
     * @type {string}
     * @memberof BookDto
     */
    isbn?: string | null;
    /**
     * @type {string}
     * @memberof BookDto
     */
    publishedDate?: string;
}
